//
//  TimeZone.swift
//  microcosm-swift-1
//
//  Created by 緒形雄二 on 2024/02/05.
//

import Foundation

// タイムゾーン一覧
public class TimeZoneConst {
    static var timezones = [
       "Africa/Johannesburg (+2:00)",
       "Africa/Lagos (+1:00)",
       "Africa/Windhoek (+1:00)",
       "America/Adak (-10:00)",
       "America/Anchorage (-9:00)",
       "America/Argentina/Buenos_Aires (-3:00)",
       "America/Bogota (-5:00)",
       "America/Caracas (-4.5:00)",
       "America/Chicago (-6:00)",
       "America/Denver (-7:00)",
       "America/Godthab (-3:00)",
       "America/Guatemala (-6:00)",
       "America/Halifax (-4:00)",
       "America/Los_Angeles (-8:00)",
       "America/Montevideo (-3:00)",
       "America/New_York (-5:00)",
       "America/Noronha (-2:00)",
       "America/Phoenix (-7:00)",
       "America/Santiago (-4:00)",
       "America/Santo_Domingo (-4:00)",
       "America/St_Johns (-3.30)",
       "Asia/Baghdad (+3:00)",
       "Asia/Baku (+4:00)",
       "Asia/Beirut (+2:00)",
       "Asia/Dhaka (+6:00)",
       "Asia/Dubai (+4:00)",
       "Asia/Irkutsk (+9:00)",
       "Asia/Jakarta (+7:00)",
       "Asia/Kabul (+4.30)",
       "Asia/Kamchatka (+12:00)",
       "Asia/Karachi (+5:00)",
       "Asia/Kathmandu (+5:45)",
       "Asia/Kolkata (+5:30)",
       "Asia/Krasnoyarsk (+8:00)",
       "Asia/Omsk (+7:00)",
       "Asia/Rangoon (+6:30)",
       "Asia/Shanghai (+8:00)",
       "Asia/Tehran (+3:30)",
       "Asia/Tokyo (+9:00)",
       "Asia/Vladivostok (+11:00)",
       "Asia/Yakutsk (+10:00)",
       "Asia/Yekaterinburg (+6:00)",
       "Atlantic/Azores (-1:00)",
       "Atlantic/Cape_Verde (-1:00)",
       "Australia/Adelaide (+9:30)",
       "Australia/Brisbane (+10:00)",
       "Australia/Darwin (+9:30)",
       "Australia/Eucla (+8:45)",
       "Australia/Lord_Howe (+10:30)",
       "Australia/Sydney (+10:00)",
       "Europe/Berlin (+1:00)",
       "Europe/London (0:00)",
       "Europe/Moscow (+4:00)",
       "Pacific/Apia (+13:00)",
       "Pacific/Auckland (+12:00)",
       "Pacific/Chatham (+12:45)",
       "Pacific/Easter (-6:00)",
       "Pacific/Gambier (-9:00)",
       "Pacific/Honolulu (-10:00)",
       "Pacific/Kiritimati (+14:00)",
       "Pacific/Majuro (+12:00)",
       "Pacific/Marquesas (-9.30)",
       "Pacific/Norfolk (+11:30)",
       "Pacific/Noumea (+11:00)",
       "Pacific/Pago_Pago (-11:00)",
       "Pacific/Pitcairn (-8:00)",
       "Pacific/Tongatapu (+13:00)",
       "UTC (+0:00)",
    ]
    
    static var timezone_time = [
       2,
       1,
       1,
       -10,
       -9,
       -3,
       -5,
       -4.5,
       -6,
       -7,
       -3,
       -6,
       -4,
       -8,
       -3,
       -5,
       -2,
       -7,
       -4,
       -4,
       3.5,
       4,
       2,
       6,
       4,
       9,
       7,
       4.5,
       12,
       5,
       5.75,
       5,5,
       8,
       7,
       6.5,
       8,
       3.5,
       9,
       11,
       10,
       6,
       1,
       -1,
       9.5,
       10,
       9.5,
       8.75,
       10.5,
       10,
       1,
       0,
       4,
       13,
       12,
       12.75,
       -6,
       -9,
       -10,
       14,
       12,
       -9.5,
       11.5,
       11,
       -11,
       08,
       13,
       0,
    ]
    
    static func TimeZoneSearch(content: String) -> Int {
        if (content == "JST") {
            return 38
        }
        for (index, s) in TimeZoneConst.timezones.enumerated() {
            if (s.contains(content)) {
                return index
            }
        }
        return -1
    }
}
